### ISSUE TITLE
"TypeError: Cannot read property 'setMaxListeners' of undefined"

### ISSUE THREAD

**Issue by nicgord** [nabbl/node-red-contrib-google-home-notify#1]
I love the idea for this and am keen to get working...

I am receiving the following error in the debug window....

Any ideas?

**Comment by nicgord** [comment]
Just an update, I selected a language that was not default and error gone.

Thanks for this add on... it has changed my life!

**Comment by torinnguyen** [comment]
duplicate of this issue #2
