### ISSUE TITLE
0.0.4 not working. Error

### ISSUE THREAD

**Issue by korniza** [nabbl/node-red-contrib-google-home-notify#4]
I get an error when i simple try to test google notify 

`"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"`
I have placed the IP of the google Home device but it reports under the box on node-red "please creeate & select a config node:.
As I am new to node-red, it may be my fault. Is something I missing (dependencies for example)?
please help!

**Comment by nabbl** [comment]
Do you have more informations about what Node-Version you are using?

**Comment by korniza** [comment]
24 Oct 21:32:15 - [info] Node-RED version: v0.17.5
24 Oct 21:32:15 - [info] Node.js  version: v4.8.4
24 Oct 21:32:15 - [info] Linux 4.4.0-97-generic x64 LE
24 Oct 21:32:15 - [info] Loading palette nodes
24 Oct 21:32:16 - [info] Dashboard version 2.5.1 started at /ui

**Comment by jenskastensson** [comment]
I'm running NodeJs 4 too I've
modified node_modules\google-home-notify\google-home-notifier.js
Add line 0
'use strict';

Change line 32 to
Googletts(text, language, 1).then(function (url) {

**Comment by nabbl** [comment]
Yes. When you are using a Node-version smaller than v7 you need to set "use strict".

Maybe I should change the required node version in the package.json or set use strict in the js file.

**Comment by jenskastensson** [comment]
Personally I would appreciate native support of Node4!

**Comment by korniza** [comment]
it worked! thanks for help! it would be great to check node version

**Comment by nabbl** [comment]
Should be fixed in the newest version (0.0.5)
