### ISSUE TITLE
Suggestion: Sound level

### ISSUE THREAD

**Issue by korniza** [nabbl/node-red-contrib-google-home-notify#5]
Is it possible to adjust the volume of device on every notification? It is nice especially if we need to send a warning notification or adjust the volume on resting hours.

**Comment by nabbl** [comment]
Definitely possible. Going to look into this

**Comment by nabbl** [comment]
I looked into this a little bit more. The Google Home (or any chromecast device) definitely supports to set the volume when you want to play sound.

But I use a wrapper service to call the API (https://github.com/thibauts/node-castv2-client) and this does not currently support setting the volume.
