### ISSUE TITLE
Can't choose language

### ISSUE THREAD

**Issue by k20human** [nabbl/node-red-contrib-google-home-notify#6]
Hi,

When we add a new google home notifier config we can't choose our language

**Comment by nabbl** [comment]
Can I have more information?

What nodejs and nodered version are you using? What happens exactly when
you try to choose the language?

**Comment by k20human** [comment]
Ok strange, i try to reproduce the issue this morning but now i can choose another language in the list ...

![image](https://user-images.githubusercontent.com/17319102/32769225-4b7716fe-c91b-11e7-9b31-c6f0bdae43b8.png)

I think you can close this issue

**Comment by jenskastensson** [comment]
I think I've seen this issue too (NodeJs v4). From what I can recall: when the configuration is opened the first time, no languages were listed. After Deploy / Save of the project  the languages are listed.

**Comment by k20human** [comment]
For information i use NodeJS v8 and yes this is the same behaviour
