### ISSUE TITLE
uncaught exception crashes node-red

### ISSUE THREAD

**Issue by moonlitknight** [nabbl/node-red-contrib-google-home-notify#7]
My node-red exited with the following log...
Error: connect EHOSTUNREACH 192.168.1.35:8009
15 Nov 14:19:46 - [red] Uncaught Exception:
15 Nov 14:19:46 - Error: connect EHOSTUNREACH 192.168.1.35:8009
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

On the basis that 192.168.1.35 is my Google Home, I'm guessing it stems from this module.

**Comment by nabbl** [comment]
Well that's not good. Currently this happens if the IP is wrong. I am
working on a fix.

**Comment by jenskastensson** [comment]
Thanks @nabbl , looking forward to the fix! I have the same problem.

**Comment by nabbl** [comment]
Should be fixed in the newest version (0.0.5)
There is now also an error message displayed on the node when the IP is unreachable.
