### ISSUE TITLE
Problem with ping and speed:  Ping Alive is always false

### ISSUE THREAD

**Issue by jenskastensson** [nabbl/node-red-contrib-google-home-notify#8]
Hi and thanks for the update.
I tried it today, but I doesn't work on my system. My observations:
The ping.sys.probe call always return "Alive=false" on my system. So it is impossible to use the latest build. I tried to replace ping with net.Socket(); and it works fine. I think maybe the ping is platform dependent but 'net' should work on all platforms. Do you mind looking into changing?

Also there's a problem with the speed variable, see below
13 Dec 16:47:23 - [info] Node-RED version: v0.17.5
13 Dec 16:47:23 - [info] Node.js  version: v6.11.2
13 Dec 16:47:23 - [info] Linux 3.2.40 arm LE

--------------------------------------------------
google_home_notifier.js

var net = require('net');
..
var clienttcp = new net.Socket();
clienttcp.connect(8009, host, function() {
        client.connect(host, function () {
          client.launch(DefaultMediaReceiver, function (err, player) {
            var media = {
              contentId: url,
              contentType: 'audio/mp3',
              streamType: 'BUFFERED' // or LIVE
            };
            player.load(media, {
              autoplay: true
            }, function (err, status) {
              client.close();
              callback('Device notified');
            });
          });
        });

});

**Also the speed variable causes an error, can we set it 1 for now?** 
  var getSpeechUrl = function (text, host, callback) {
    Googletts(text, language, **1**).then(function (url) {  // TypeError: Cannot read property 'speed' of undefined
      onDeviceUp(host, url, function (res) {
        callback(res);
      });
    }).catch(function (err) {
      emitter.emit("error", err);
    });
  };

**Comment by nabbl** [comment]
thank you. should be fixed with newest version (0.0.6)

**Comment by jenskastensson** [comment]
Thx looks good
